package.json
Parallel-stream switch to basic-queue for more reliability in some situations where millions of tiles are being copied.
=> Bump parallel-stream

bin/tilelive-copy, lib/stream-list.js, lib/stream-put.js, lib/stream-pyramid.js, lib/stream-scanline.js, lib/stream-util.js, lib/tilelive.js, test/copy.test.js, test/stream-list.test.js, test/stream-pyramid.test.js, test/stream-scanline.test.js, test/stream-util.test.js, test/stream-write.test.js, test/timedsource.js
Adds retry option to the readable and writable tile streams with exponential backoff.
@rclark will you need anything else here? Also,  **question:** should a retry option apply to both read/write streams or should there be seperate options to enable retry on each stream?
=> Copy retry

lib/tilelive.js, test/copy.test.js, test/stream-scanline.test.js, test/timedsource.js
Adds a configuration option to `tilelive.copy` that allows you to specify a timeout value (in ms, defaults to 60000). If the progress-stream does not change in this period, the copy operation is halted and an error is thrown.
cc @yhahn
=> Copy timeout

lib/tilelive.js, test/copy.test.js
Allows the caller of `tilelive.copy` to provide a transform stream. If provided, its inserted into the copy pipeline and could allow the caller to "spy" on the tiles as they are copied.
refs #130 #129 
cc @yhahn @tmcw
=> Intermediate transform stream

.travis.yml, lib/tilelive.js, test/copy.test.js
A syntax error in `tilelive.copy` and loose tests meant that #128 **always** timed out at the specified interval.
Fixes the syntax error and adds a test for it.
=> Confirm that copy operation does not ALWAYS timeout at specified time

bin/tilelive-copy, test/copy.test.js
Adds `--timeout` flag for https://github.com/mapbox/tilelive.js/pull/128 to `tilelive-copy`.
=> Expose timeout copy option to command util

API.md
I was bitten by issue #42 when trying to implement a tilelive TileSource that used vector tiles, which by their nature are sparse. (My backend would faithfully emit error messages for missing tiles, but with a different wording which made tilelive crash out rather than just skip the tile.) Until the actual issue is resolved (which would mean bumping the API version and rewriting all tilelive implementations, I guess) it should be made an explicit part or the API doc.
=> Make implicit API expectation explicit

lib/tilelive.js, package.json, test/auto.test.js, test/load.test.js
Fixes autoloading when a protocol includes the `+`. Expects that the handler is the early part of the protocol (e.g. `tilejson+http` => load via `tilejson`).
cc @mick
=> Autoloading: handle protocols with +

lib/tilelive.js, test/auto.test.js
missing the 2nd argument `true` to `url.parse` in `tilelive.auto()` 
[`tilvelive.copy()` uses the parsed return from `tilelive.auto`](https://github.com/mapbox/tilelive/blob/master/lib/tilelive.js#L332-L333), downstream other tilvelive modules only check to see if uri is parsed and expect that to mean the querystring is parsed too.
cc @yhahn
=> parse the querystring everywhere we parse the url

bin/tilelive-copy, lib/stream-list.js, lib/stream-put.js, lib/stream-pyramid.js, lib/stream-scanline.js, lib/stream-util.js, lib/tilelive.js, test/copy.test.js, test/stream-util.test.js
- Always: changes getTileRetry and putTileRetry util functions to take a stream object and emit `slow` events when a tile op exceeds the `slowTime` threshold. `slowTime` threshold defaults to 60s.
- Optional: if `options.slow = <time in ms>` is passed to `tilelive.copy()`, copy sets the threshold and adds handlers for outputting to `stderr` whenever the `slow` event is emitted.
- Exposes this option to tilelive-copy bin.
This would start 5.10.x 
@rclark :eyes: ?
=> Add logging to stderr for slow tiles (get/put) during a tilelive-copy

test/copy.test.js
The `--slow` test added in 93e95a43dddcec171d9dbe364bb579688fb32d90 is failing for me because it is reporting the `put` as slow, not the `get`.
Judging by the equivalent API level test in f3538d47eee18ac5bd4dbd774784541324601099, which allows either method, this is probably expected, so this updates the expected result to allow either method.
=> We don't know if it will be the get or put that reports as slow

bin/tilelive-copy, lib/tilelive.js, test/copy.test.js
If a source provides a `createZXYStream()` method, use it for copying in list mode if no explicit list is provided.
cc @rclark
=> Use source.createZXYStream() with copy `--list` option if no list provided

bin/tilelive-copy
Adds `--exit` flag for optionally forcing a `process.exit(0)` when tilelive-copy complete successfully rather than waiting for node to exit. Addresses some resources being held onto at the end of a copy leading to hangs.
=> Optionally: exit 0 on tilelive-copy

.travis.yml, package.json
This passes all tests on node 4 so I think we can relax the restriction?
=> Relax engine version restrictions

lib/tilelive.js, test/copy.test.js
There wasn't error handling on the transform stream, which would previously just throw when the transform stream errored.
cc/ @rclark for a quick review if you could.
=> Add error handling for the transform stream

lib/tilelive.js, package.json, test/copy.test.js
- allows stream-combiner to be used as a transform stream
stream-combiner doesn't produce a transform stream, it produces a stream that quacks like a transform stream though. So no more `instanceof`, just ask it to quack :smile_cat: 
cc/ @rclark
=> Allow transform-like streams to be used

bin/tilelive-copy
Commit 878d4169dc38995bdfcacab6e223a6441a41d1bb removed the use of a deprecated function to print output progress, but at the expense of making progress scroll endlessly rather than staying on one line. This PR replaces that with process.stdout.write, which seems to be the accepted approach according to the node docs: https://nodejs.org/api/process.html#process_process_stdout
=> Log progress to a single line using a non-deprecated function

lib/tilelive.js, test/load.test.js
Sometimes modules do not require a full path,
and can use shorter version, e.g.   overzoom://?source=blah
which results in the null pathname, which fails in the unescape.
=> Handle null uri.pathname bug

README.md
Add add tilelive-postgis — a tilelive source for outputting PBF-encoded tiles from PostGIS.
=> add tilelive-postgis

lib/stream-deserialize.js, lib/stream-serialize.js, lib/stream-util.js, test/copy.test.js, test/stream-serialize.test.js, test/stream-util.test.js
The serialtiles serializer is written like a pretty reasonable newline delimited stream writer with the one exception that in the final `_flush` case it decides to not write a trailing newline. This causes all kinds of headaches for anyone attempting to resume or append to a previously written serialtiles files.
What happens now (newlines visualized for ease). Note that the last line does not have a trailing `\n`.
```
JSONBREAKFASTTIME\n
{ ... }\n
{ ... }\n
{ ... }
```
Now let's append to this stream assuming we can write in a way consistent with the previous writes...
```
JSONBREAKFASTTIME\n
{ ... }\n
{ ... }\n
{ ... }{ ... }
{ ... }\n
{ ... }\n
...
```
Not great.
No big deal, appenders can just write lines with a prefixed newline! `\n{ ... }`
```
JSONBREAKFASTTIME\n
{ ... }\n
{ ... }\n …
```
=> Append-friendlier serial tiles serializer

CHANGELOG.md, lib/tilelive.js, package.json
Updates to work with S3 client of aws-sdk 2.1562.0:
* Use the default value of HighWaterMark for the WriteStream interface. With the updated aws-sdk version, the HighWaterMark setting was causing write timeouts.
* New version of aws-sdk does not reliably call the callback fuction of put_object. tilelive depended on that call back to count the number tiles being written. When the callback was not being called tilelive would hang. The solution is just use the finish event that tilelive to indicate that all of the tiles have been written. If an error occures tilelive will catch the error event.
=> Telemetraf-3602: Update to use aws-sdk >= 2.1562
